server:
  port: 8180
  address: localhost
  #ssl:
    #key-store: classpath:.keystore
    #key-store-password: 123456
    #key-store-type: JKS
    #key-alias=

spring:
  application:
    name: pos-test
  redis:
    host: 192.168.1.11
    port: 6379
    password: root
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
  datasource:
    url: jdbc:mysql://192.168.1.188:3306/pos?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017/demo
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    #root: DEBUG
    org.hibernate: ERROR
    org.springframework:
      #web: DEBUG
      transaction.interceptor: ERROR
